from aiogram.dispatcher.filters.state import StatesGroup, State

class new(StatesGroup):
	uzen = State()
	enuz = State()
	ruuz = State()
	uzru = State()
	uzge = State()
	geuz = State()
	aruz = State()
	uzar = State()
	uztur = State()
	turuz = State()
	hiuz = State()
	uzhi = State()
	uzfr = State()
	fruz = State()
	chsmuz = State()
	uzchsm = State()
	uzchtr = State()
	chtruz = State()
	tjuz = State()
	uztj = State()
	uzkg = State()
	kguz = State()
	kouz = State()
	uzko = State()
	uzka = State()
	kauz = State()
	adss = State()
